export const rows = [
  {
    id: 1,
    time: "11:58",
    date: "12.06.2023",
    contentType: "order",
    content: "Нове замовлення від Колесник М.",
    status: "unread",
  },
  {
    id: 2,
    time: "13:58",
    date: "12.06.2023",
    contentType: "feedback",
    content: "Новий відгук від Колесник М.",
    status: "read",
  },
  {
    id: 3,
    time: "11:58",
    date: "12.06.2023",
    contentType: "order",
    content: "Нове замовлення від Колесник М.",
    status: "read",
  },
  {
    id: 4,
    time: "11:58",
    date: "12.06.2023",
    contentType: "order",
    content: "Нове замовлення від Колесник М.",
    status: "unread",
  },
  {
    id: 5,
    time: "11:58",
    date: "12.06.2023",
    contentType: "order",
    content: "Нове замовлення від Колесник М.",
    status: "unread",
  },
  {
    id: 6,
    time: "11:58",
    date: "12.06.2023",
    contentType: "order",
    content: "Нове замовлення від Колесник М.",
    status: "read",
  },
  {
    id: 7,
    time: "13:58",
    date: "12.06.2023",
    contentType: "feedback",
    content: "Новий відгук від Колесник М.",
    status: "read",
  },
  {
    id: 8,
    time: "11:58",
    date: "12.06.2023",
    contentType: "order",
    content: "Нове замовлення від Колесник М.",
    status: "read",
  },
  {
    id: 9,
    time: "13:58",
    date: "12.06.2023",
    contentType: "feedback",
    content: "Новий відгук від Колесник М.",
    status: "unread",
  },
  {
    id: 17,
    time: "13:58",
    date: "12.06.2023",
    contentType: "feedback",
    content: "Новий відгук від Колесник М.",
    status: "read",
  },
  {
    id: 18,
    time: "11:58",
    date: "12.06.2023",
    contentType: "order",
    content: "Нове замовлення від Колесник М.",
    status: "unread",
  },
  {
    id: 19,
    time: "13:58",
    date: "12.06.2023",
    contentType: "feedback",
    content: "Новий відгук від Колесник М.",
    status: "unread",
  },
]
